# Generated by Django 5.2.11 on 2026-02-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank='True', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='images',
            field=models.ImageField(blank='True', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank='True'),
        ),
    ]
