# Generated by Django 5.2.11 on 2026-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_file_alter_lesson_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.ImageField(blank='True', upload_to='images_course'),
        ),
    ]
